<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'read more' => 'read more',
    'Latest news' => 'Latest news',
    'all news' => 'all news',
    'Activities' => 'Activities',
    'Time' => 'Time',
    'Currency' => 'Currency',
    'Tourism Info Centers' => 'Tourism Info Centers',
    'The Tourist Information Centres are working in Stepanakert, in the cultural capital of Karabakh – Shoushi, in Tigranakert, the House-Museum of Nikol Duman (in the village Tsahkashat).' => 'The Tourist Information Centres are working in Stepanakert, in the cultural capital of Karabakh – Shoushi, in Tigranakert, the House-Museum of Nikol Duman (in the village Tsahkashat).',
    'Events' => 'Events',
    'Location' => 'Location',
    'VISIT EVENT' => 'VISIT EVENT',
    'all events' => 'all events',
    'Contact us' => 'Contact us',
    'Calendar' => 'Calendar',
    'About Artsakh' => 'About Artsakh',
    'Republic of Artsakh' => 'Republic of Artsakh',
    'From the Bronze age to Nowadays' => 'From the Bronze age to Nowadays',
    'Geographic facts' => 'Geographic facts',
    'Religion' => 'Religion',
    'National holidays and festivals' => 'National holidays and festivals',
    'Discover' => 'Discover',
    'Regions' => 'Regions',
    'Culture' => 'Culture',
    'Cuisine' => 'Cuisine',
    'Carpets' => 'Carpets',
    'Fancywork' => 'Fancywork',
    'Karabakh horses' => 'Karabakh horses',
    'Multicultural heritage of Artsakh' => 'Multicultural heritage of Artsakh',
    'Travel routes' => 'Travel routes',
    'On your way to Stepanakert' => 'On your way to Stepanakert',
    'Southern travel route' => 'Southern travel route',
    'Northern Travel route' => 'Northern Travel route',
    'Stepanakert-Martakert highway' => 'Stepanakert-Martakert highway',
    'Plan your trip' => 'Plan your trip',
    'Getting there' => 'Getting there',
    'Entry formalities' => 'Entry formalities',
    'Acommodation' => 'Acommodation',
    'Useful information' => 'Useful information',
    'Find me a guide' => 'Find me a guide',
    'Touroperators' => 'Touroperators',
    'Transportation companies' => 'Transportation companies',
    'FAQ' => 'FAQ',
    'Things to do' => 'Things to do',
    'Cafes and Restaurants' => 'Cafes and Restaurants',
    'Museums and Theatres' => 'Museums and Theatres',
    'Cultural sightseeing' => 'Cultural sightseeing',
    'Archaeological sightseeing' => 'Archaeological sightseeing',
    'Agrotourism' => 'Agrotourism',
    'Adventures' => 'Adventures',
    'Religious tourism' => 'Religious tourism',
    'We would be more than happy to help you. Our team advisor are 24/7 at your service to help you.' => 'We would be more than happy to help you. Our team advisor are 24/7 at your service to help you.',
    '24/2 Lusavorich St - Stepanakert' => '24/2 Lusavorich St - Stepanakert',
    'Upcoming Events' => 'Upcoming Events',
    'Site Map' => 'Site Map',
    'Follow us:' => 'Follow us:',
    'Place' => 'Place',
    'Date Time' => 'Date Time',
    'Tickets' => 'Tickets',
    'FREE' => 'FREE',
    'AMD' => 'AMD',
    'Events calendar' => 'Events calendar',
    'results found' => 'results found',
    'Next event' => 'Next event',
    'Date' => 'Date',
    'VISIT NEWS' => 'VISIT NEWS',
    'News list' => 'News list',
    'Activity' => 'Activity',
    'show all' => 'show all',
    'Search results' => 'Search results',
    'Search' => 'Search',
    'No results found' => 'No results found',
    'Get our neewsletter' => 'Get our neewsletter',
    'E-mail' => 'E-mail',
    'Enter your email address for our mailing list to keep yourself updated.' => 'Enter your email address for our mailing list to keep yourself updated.',
    'Outdoor activities' => 'Outdoor activities',
    'Artsakh gives an opportunity for all stakeholders to try adventure tourism.Karabakh is not famous for its rich ancient history and culture, but also the freedom-loving, even rebellious, adventurous kind of native.' => 'Artsakh gives an opportunity for all stakeholders to try adventure tourism.Karabakh is not famous for its rich ancient history and culture, but also the freedom-loving, even rebellious, adventurous kind of native.',
    'Hiking' => 'Hiking',
    'Fishing' => 'Fishing',
    'Flights above Artsakh' => 'Flights above Artsakh',
    'Mountain biking' => 'Mountain biking',
];
